// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ushio.Infrastructure.Database;

namespace Ushio.Infrastructure.Migrations
{
    [DbContext(typeof(UshioDbContext))]
    [Migration("20210725003023_InitialFightingGameVodSchema")]
    partial class InitialFightingGameVodSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("uuid-ossp")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Ushio.Data.DatabaseModels.FightingGameVod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CharacterP1")
                        .HasColumnType("text");

                    b.Property<string>("CharacterP2")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateAddedToRepo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateUploaded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameName")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Player1")
                        .HasColumnType("text");

                    b.Property<string>("Player2")
                        .HasColumnType("text");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FightingGameVods");
                });

            modelBuilder.Entity("Ushio.Data.DatabaseModels.VideoClip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VideoClips");
                });
#pragma warning restore 612, 618
        }
    }
}
