name: Ushio-BuildAndDeploy

on: push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Files
     uses: actions/checkout@v2

   - name: Setup dotnet
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: "5.0.402"

   - run: dotnet build
   - run: dotnet test

 deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Files
     uses: actions/checkout@v2

   - name: Copy files via SCP
     uses: appleboy/scp-action@master
     env:
      HOST: ${{ secrets.DROPLETHOST }}
      USERNAME: ${{ secrets.DROPLETUSER }}
      PORT: ${{ secrets.DROPLETPORT }}
      KEY: ${{ secrets.SSHKEY }}
      PASSPHRASE: ${{ secrets.SSHPASSPHRASE }}
     with:
      source: "."
      target: "/home/gr8stalin/ushio"

   - name: Start bot
     uses: appleboy/ssh-action@master
     with:
      HOST: ${{ secrets.DROPLETHOST }}
      USERNAME: ${{ secrets.DROPLETUSER }}
      PORT: ${{ secrets.DROPLETPORT }}
      KEY: ${{ secrets.SSHKEY }}
      PASSPHRASE: ${{ secrets.SSHPASSPHRASE }}

   
