name: Ushio-TestAndDeploy

on: push

jobs:
 test-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Files
     uses: actions/checkout@v2

   - name: Setup dotnet and Test
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: "5.0.402"

   - run: dotnet build --configuration Release
   - run: dotnet test
      
   - name: Publish Bot
     run: dotnet publish -c Release --output Release

   - name: Copy files via SCP
     uses: appleboy/scp-action@master
     env:
      HOST: ${{ secrets.DROPLETHOST }}
      USERNAME: ${{ secrets.DROPLETUSER }}
      PORT: ${{ secrets.DROPLETPORT }}
      KEY: ${{ secrets.SSHKEY }}
      PASSPHRASE: ${{ secrets.SSHPASSPHRASE }}
     with:
      source: "./Release"
      target: "/home/gr8stalin/Ushio"

   - name: Toggle bot
     uses: appleboy/ssh-action@master
     with:
      HOST: ${{ secrets.DROPLETHOST }}
      USERNAME: ${{ secrets.DROPLETUSER }}
      PORT: ${{ secrets.DROPLETPORT }}
      KEY: ${{ secrets.SSHKEY }}
      PASSPHRASE: ${{ secrets.SSHPASSPHRASE }}
      SCRIPT: togglebot.sh

   
